name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -e

            export NVM_DIR="$HOME/.nvm"

            if [ -s "$NVM_DIR/nvm.sh" ]; then
              source "$NVM_DIR/nvm.sh"
            fi

            nvm use 22

            echo "Node: $(node -v)"
            echo "NPM: $(npm -v)"
            echo "Node path: $(which node)"

            cd /home/ubuntu/chronilogix-wp

            git checkout main
            git pull origin main

            npm i
            npm run build

            pm2 restart my-next-app
